name: Build mod zip and release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create mod zip
        run: |
          mkdir -p build/"Unnamed Balatro Mod"
          shopt -s extglob
          cp -R !(build|.git|.github) build/"Unnamed Balatro Mod"/
          cd build
          zip -r "UnnamedBalatroMod-${GITHUB_REF_NAME}.zip" "Unnamed Balatro Mod"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/"UnnamedBalatroMod-${GITHUB_REF_NAME}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

